# when particluar task's presence is not that much important in that case we  will ignore_errors
# here errors caused by that task is ignored by ansible and keeps moving to next tasks
---
- hosts: dev
  tasks:
   - name: create a user
     user:
        name: amar
        state: present
   - name: install git
     yum:
       name: git
       state: latest
   - name: start service
     service:
       name: git
       state: started
     ignore_errors: yes

   - name: install httpd
     package:
       name: httpd
       state: installed
   - name: start service for httpd
     service:
       name: httpd
       state: started