#fail a task forcefully fail_when condition

---
- hosts: app
  tasks:
  - name: Making sure the /tmp has more than 1gb
    shell: "df -h /tmp|grep -v Filesystem|awk '{print $4}'|cut -d G -f1"
    register: tmpspace
  - debug:
      var: tmpspace.stdout
    failed_when: "tmpspace.stdout|float < 1"
  - name: install httpd if requirements meet
    yum:
     name: httpd
     state: installed
# if tmp space is less than 1  we are failing httpd installation intentionally  if a task fails as ansible stops next tasks
  - name: Making sure the /opt has more than 4gb
    shell: "df -h /opt|grep -v Filesystem|awk '{print $4}'|cut -d G -f1"
    register: tmpspace
    failed_when: "tmpspace.stdout|float < 4"

  - name: Making sure the Physical Memory more than 2gb
    shell: "cat /proc/meminfo|grep -i memtotal|awk '{print $2/1024/1024}'"
    register: memory
    failed_when: "memory.stdout|float < 2"