---
- hosts: all
  tasks:
   - name: create user
     user:
       name: "{{ item }}"
       state: present
     with_items:
      - vamsi
      - thor
      - hulk

   - name: create files
     file:
       path: "{{ item }}"
       state: touch
     with_items:
         - /tmp/file1
         - /tmp/file2
         - /tmp/file3
   - name: install applications
     package:
       name: "{{ item }}"
       state: installed
     with_items:
       - git
       - docker
       - httpd

# passing variables from the playbook for use cases like creating multiple users
# here yum is not used becoz for multiple installs package  module is used